# Generated by Django 5.2.1 on 2025-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=100)),
                ("dept_code", models.CharField(max_length=10)),
                ("dept_head", models.CharField(max_length=100)),
            ],
        ),
    ]
